name: ProjectesAndorra
favicon: null
layout_spectrum: 0.75528
typography_spectrum: 0.75309
title: ProjectesAndorra
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d111a'
    - '#6ba1ed'
    - '#ffffff'
    - '#6a798c'
    - '#c9d2dc'
  brandStrength: 0.375
  lightness: 0.613163448870182
  saturation: 0.33432933245785534
  rhythmicContrast: 1
purpose: []
